export const userType = {
    SET_INITIAL_USER_DATE : 'SET_INITIAL_USER_DATE',
    SET_EDIT_INFO_OBJ : 'SET_EDIT_INFO_OBJ',
    UPDATE_USER_DATA : 'UPDATE_USER_DATA',
    ADD_NEW_USER : 'ADD_NEW_USER',
    DELETE_USER : 'DELETE_USER'
}